---
- name: Converge
  hosts: all

  pre_tasks:
    - include_vars: vars.yml
    
  tasks:
    # - name: Install base packages
    #   include_role:
    #     name: base_packages

    # - name: Install docker
    #   include_role:
    #     name: docker

    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Install docker-compose
      include_role:
        name: docker-compose
      vars:
        docker_compose_version: 1.16.0

    - name: Include somnoynadno.dockerized_services role
      include_role:
        name: somnoynadno.dockerized_services
