---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint: |
  set -e
  yamllint .

platforms:
  - name: ubuntu-bionic
    image: daangn/dind:ubuntu-18.04
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

provisioner:
  name: ansible

verifier:
  name: ansible
