---
dependency:
  name: galaxy
  requirements_file: requirements.yml

driver:
  name: docker

lint: |
  set -e
  yamllint -c .yamllint.yml .

platforms:
  - name: ubuntu-bionic
    image: daangn/dind:ubuntu-18.04
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  - name: ubuntu-focal
    image: kvergun/ubuntu-20.04-dind:latest
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

provisioner:
  name: ansible

verifier:
  name: ansible
