---
dockerized_services_user: "{{ lookup('env', 'USER') }}"
dockerized_services_base_folder: "/home/{{ dockerized_services_user }}/services"

dockerized_services_list: 
  - name: "stub-{{ lookup('env', 'HOSTNAME') }}-up"
    repository: "https://github.com/somnoynadno/dockerized-service-stub"
  - name: "stub-{{ lookup('env', 'HOSTNAME') }}-down"
    repository: "https://github.com/somnoynadno/dockerized-service-stub"
    up: false # this service should be down

dockerized_services_management_enabled: true
