---
__distro: "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}"

dockerized_services_user: root
dockerized_services_group: root
dockerized_services_base_folder: "/home/{{ dockerized_services_user }}/services"

dockerized_services_list: 
  - name: "stub-{{ __distro }}-up"
    repository: "https://github.com/somnoynadno/dockerized-service-stub"
  - name: "stub-{{ __distro }}-down"
    repository: "https://github.com/somnoynadno/dockerized-service-stub"
    up: false # this service should be down

dockerized_services_management_enabled: true
dockerized_services_skip_dependency_check: false
